# Generated by Django 5.2.4 on 2025-07-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_file", models.FileField(upload_to="resumes/")),
            ],
        ),
    ]
